# Generated by Django 5.0.9 on 2024-09-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.BigIntegerField(blank=True, default='', verbose_name='Random Number'),
            preserve_default=False,
        ),
    ]
