# Generated by Django 5.0.9 on 2024-09-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.BigIntegerField(blank=True, default=999999999, verbose_name='Random Number'),
        ),
    ]
