# Generated by Django 5.0.9 on 2024-09-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StocksData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=200)),
                ('cik_str', models.PositiveIntegerField()),
                ('sector', models.CharField(max_length=75)),
                ('industry', models.CharField(max_length=200)),
                ('market_cap', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StockSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_ticker', models.CharField(default='', max_length=10)),
                ('company_name', models.CharField(default='', max_length=500)),
                ('currency', models.CharField(default='', max_length=50)),
                ('currency_name', models.CharField(default='', max_length=100)),
                ('base_currency', models.CharField(default='', max_length=25)),
                ('base_currency_name', models.CharField(default='', max_length=100)),
                ('market_type', models.CharField(default='', max_length=25)),
                ('security_type', models.CharField(default='', max_length=25)),
                ('api_call_symbol', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
