# Generated by Django 4.2.11 on 2024-04-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StocksData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('companyName', models.CharField(max_length=200)),
                ('cik_str', models.PositiveIntegerField()),
                ('sector', models.CharField(max_length=75)),
                ('industry', models.CharField(max_length=200)),
                ('marketCap', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='stocksearch',
            name='companyName',
            field=models.CharField(max_length=200),
        ),
    ]
