# Generated by Django 4.2.11 on 2024-06-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0002_stocksdata_alter_stocksearch_companyname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocksearch',
            old_name='ticker',
            new_name='publicTicker',
        ),
        migrations.AddField(
            model_name='stocksearch',
            name='apiCallSymbol',
            field=models.CharField(default=1234, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocksearch',
            name='baseCurrency',
            field=models.CharField(default=1234, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocksearch',
            name='baseCurrencyName',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocksearch',
            name='currency',
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocksearch',
            name='currencyName',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocksearch',
            name='marketType',
            field=models.CharField(default=1234, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocksearch',
            name='securityType',
            field=models.CharField(default=1234, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocksearch',
            name='companyName',
            field=models.CharField(max_length=500),
        ),
    ]
