# Generated by Django 4.2.11 on 2024-06-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0003_rename_ticker_stocksearch_publicticker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksearch',
            name='apiCallSymbol',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='stocksearch',
            name='baseCurrency',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='stocksearch',
            name='baseCurrencyName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stocksearch',
            name='companyName',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='stocksearch',
            name='currency',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stocksearch',
            name='currencyName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stocksearch',
            name='marketType',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='stocksearch',
            name='publicTicker',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='stocksearch',
            name='securityType',
            field=models.CharField(default='', max_length=25),
        ),
    ]
