# Generated by Django 4.2.11 on 2024-08-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0004_alter_stocksearch_apicallsymbol_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocksdata',
            old_name='companyName',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='stocksdata',
            old_name='marketCap',
            new_name='market_cap',
        ),
        migrations.RenameField(
            model_name='stocksearch',
            old_name='apiCallSymbol',
            new_name='api_call_symbol',
        ),
        migrations.RenameField(
            model_name='stocksearch',
            old_name='baseCurrency',
            new_name='base_currency',
        ),
        migrations.RenameField(
            model_name='stocksearch',
            old_name='baseCurrencyName',
            new_name='base_currency_name',
        ),
        migrations.RenameField(
            model_name='stocksearch',
            old_name='companyName',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='stocksearch',
            old_name='currencyName',
            new_name='currency_name',
        ),
        migrations.RenameField(
            model_name='stocksearch',
            old_name='marketType',
            new_name='market_type',
        ),
        migrations.RenameField(
            model_name='stocksearch',
            old_name='publicTicker',
            new_name='public_ticker',
        ),
        migrations.RenameField(
            model_name='stocksearch',
            old_name='securityType',
            new_name='security_type',
        ),
    ]
