# Generated by Django 5.0.9 on 2024-09-17 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='', max_length=10)),
                ('company_name', models.CharField(default='', max_length=250)),
                ('api_call_symbol', models.CharField(default='', max_length=10)),
                ('market_type', models.CharField(default='', max_length=10)),
                ('shares_owned', models.FloatField(default='', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('price_per_unit', models.FloatField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='', max_length=10)),
                ('company_name', models.CharField(default='', max_length=500)),
                ('api_call_symbol', models.CharField(default='', max_length=10)),
                ('market_type', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
