# Generated by Django 4.2.11 on 2024-06-20 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_portfolio_sharesowned'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='apiCallSymbol',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='marketType',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='apiCallSymbol',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='marketType',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='companyName',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='pricePerUnit',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='sharesOwned',
            field=models.FloatField(default='', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='ticker',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='companyName',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='ticker',
            field=models.CharField(default='', max_length=10),
        ),
    ]
