# Generated by Django 4.2.11 on 2024-08-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_portfolio_apicallsymbol_portfolio_markettype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='apiCallSymbol',
            new_name='api_call_symbol',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='companyName',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='marketType',
            new_name='market_type',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='pricePerUnit',
            new_name='price_per_unit',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='sharesOwned',
            new_name='shares_owned',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='apiCallSymbol',
            new_name='api_call_symbol',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='companyName',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='marketType',
            new_name='market_type',
        ),
    ]
